name: Test

on:
  push:
    tags:
      - 'test*'

jobs:
  modpack-info:
    runs-on: ubuntu-latest
    outputs:
      projectname: ${{ steps.info.outputs.projectname }}
      version: ${{ steps.info.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get modpack info
        id: info
        run: |
            manifestjson=`cat pax/modpack/manifest.json`
            projectname=`echo $(jq -r '.name' <<< "$manifestjson")`
            echo "::set-output name=projectname::$projectname"
            version=`echo $(jq -r '.minecraft.version' <<< "$manifestjson")`
            echo "::set-output name=version::$version"
      - name: Get tag
        id: version
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Process changelog
        run: |
          mv CHANGELOG.md pax/changelogs/${{ steps.version.outputs.tag }}.md
          cp pax/changelogs/TEMPLATE.md CHANGELOG.md
      - name: Commit changelog
        run: |
          git add .
          git config --local user.name "Juraj Hrivnak"
          git config --local user.email "juraj-hrivnak@users.noreply.github.com"
          git commit -m "Update CHANGELOG.md" -a
      - name: Push changelog
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - name: Upload changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: pax/changelogs/${{ steps.version.outputs.tag }}.md
